-- +goose Up
-- +goose StatementBegin
-- Migration: 052
-- Adds gate_level, regime_label, and vix_level columns to commercial_reports
-- for halt-mode reports generated by the R-09 circuit breaker.
-- These fields are populated only when the pipeline is in HALT mode and
-- a minimal report is generated instead of the full LLM transformation.

ALTER TABLE commercial_reports
    ADD COLUMN IF NOT EXISTS gate_level   TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS regime_label TEXT    NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS vix_level    DOUBLE PRECISION NOT NULL DEFAULT 0;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE commercial_reports
    DROP COLUMN IF EXISTS gate_level,
    DROP COLUMN IF EXISTS regime_label,
    DROP COLUMN IF EXISTS vix_level;
-- +goose StatementEnd
